### ISSUE TITLE
pyautogui.FAILSAFE

### ISSUE THREAD

**Issue by Feticones** [iholston/lol-bot#260] opened 2024-11-02 19:55 UTC
**Describe the bug**
If the bot goes ingame, the error comes and the game closes

**Version**
3.0.1

ERROR CODE:

PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.
[20:23:22] [ERROR  ] Traceback (most recent call last):
  File "C:\Users\test\Desktop\lolbot\lolbot\bot\bot.py", line 67, in run
    launcher.launch_league(
  File "C:\Users\test\Desktop\lolbot\lolbot\bot\launcher.py", line 60, in launch_league
    manual_login(username, password)
  File "C:\Users\test\Desktop\lolbot\lolbot\bot\launcher.py", line 76, in manual_login
    controller.write(username)
  File "C:\Users\test\Desktop\lolbot\lolbot\bot\controller.py", line 26, in write
    pyautogui.write(keys, interval=0.11)
  File "C:\Users\test\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 593, in wrapper
    failSafeCheck()
  File "C:\Users\test\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 1734, in failSafeCheck
    raise FailSafeException(
pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.

[20:23:22] [ERROR  ] Unknown Error. Exiting

**Comment by iholston** [comment] 2024-11-03 01:43
Interesting. Does this happen every time the bot logs in?

**Comment by xunyangjian1** [comment] 2024-11-03 01:48
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 466, in _make_request
  File "urllib3\connectionpool.py", line 1095, in _validate_conn
  File "urllib3\connection.py", line 730, in connect
  File "urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 455, in wrap_socket
  File "ssl.py", line 1041, in _create
  File "ssl.py", line 1319, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 490, in _make_request
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/iholston/lol-bot/releases/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.pyw", line 8, in <module>
  File "lolbot\view\main_window.py", line 35, in __init__
  File "lolbot\view\about_tab.py", line 17, in __init__
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 698, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/iholston/lol-bot/releases/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))

this is mine

**Comment by iholston** [comment] 2024-11-03 01:52
I'll have to look into that one as well.

**Comment by iholston** [comment] 2024-12-01 20:40
I believe both of these issues should be fixed in the latest release.

**Closed by iholston** 2024-12-01 20:40 UTC
